FROM debian:buster-20210208
MAINTAINER @maintainer@

ENV TERM xterm

# apt config:  silence warnings and set defaults
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# turn off recommends on container OS
# install required dependencies
RUN echo 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";' > \
    /etc/apt/apt.conf.d/01norecommend && \
    apt-get update && \
    apt-get -y install \
        debsecan \
        bzip2 \
        libc6-i386 \
        git \
        libfontconfig1 \
        libglib2.0-0 \
        sudo \
        nano \
        locales \
        libxext6 \
        libxrender1 \
        libxtst6 \
        libtinfo-dev \
        libgtk2.0-0 \
        build-essential \
        unzip \
        ruby \
        ruby-dev \
        pkg-config \
        libprotobuf-dev \
        protobuf-compiler \
        python-protobuf \
        python-pip && \
    pip install intelhex && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen && \
    apt-get clean && \
    ln -s /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5

# update packages with security fixes
RUN apt-get -y install $(debsecan --suite buster --format packages --only-fixed)

# Sharing the x server with docker. See:
# http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
RUN mkdir -p /home/developer && \
    echo "developer:x:1000:1000:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:1000:" >> /etc/group && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown 1000:1000 /home/developer && \
    chown -R 1000:1000 /opt

ENV USER=developer USER_ID=1000 USER_GID=1000

COPY user-mapping.sh /
RUN  chmod u+x /user-mapping.sh

ENTRYPOINT ["/user-mapping.sh"]
